name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx

    - name: Build and test
      run: |
        # Add commands to build and test your application

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo mkdir -p /tmp/deploy
          cd /tmp/deploy
          sudo cp -r $GITHUB_WORKSPACE/* .
          sudo cp -r * /var/www/html/
          cd /
          sudo rm -rf /tmp/deploy
